# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: "ubuntu-latest"

trigger:
  - "*"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "16.18.0"
    displayName: "Install Node.js"

  - script: |
      # npm install -g @ionic/cli@6.20.4
      npm install
      npm run build:pwa
    displayName: "npm install and build"

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/www"
      includeRootFolder: false
      archiveType: "zip"
      archiveFile: "$(Build.ArtifactStagingDirectory)/Warehouse.1.0.0.$(Build.BuildId).zip"
      replaceExistingArchive: true

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: "$(Build.ArtifactStagingDirectory)/Warehouse.1.0.0.$(Build.BuildId).zip"
      artifact: Warehouse
